name: Build and Deploy Web - DEV
on:
  push:
    branches:
      - master

env:
  EDGIO_ENV: dev

jobs:
  build-deploy-web:
    name: Deploy Web Dev
    environment:
      name: dev
    #      url: https://coh2-ladders-dev.web.app/
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: "14.x"
      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules-v1
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install Deps
        run: yarn install
      - name: Deploy to Firebase
        env:
          DEPLOY_TOKEN: ${{ secrets.EDGIO_DEPLOY_TOKEN}}
        # Deploy command automatically runs the build
        run: |
          edgio deploy -e $EDGIO_ENV --token $DEPLOY_TOKEN
